### ISSUE TITLE
Add syntax for examples

### ISSUE THREAD

**Issue by Carpetsmoker** [Teamwork/kommentaar#2]
Not a priority for release, but would be nice to add.

e.g.

- Single string: `{example: "Hello"}`
- Two examples: `{example: "Hello", example: "World"}`
- Special keyword: `{email}`, `{name}`, or maybe `{example: email}`, `{example: $email}` (could use [fake](https://github.com/syscrusher/fake))?

Also need to look what the OpenAPI format and tools support, exactly.

**Comment by ready4god2513** [comment]
Would love one on use cases such as `helper.Validation`.  Wasn't sure what exactly what should be there?  Should I just add the object?

```{
    errors: [
      ....
    ]
}```
