### ISSUE TITLE
Multiple response types

### ISSUE THREAD

**Issue by rafaeljusto** [Teamwork/kommentaar#27]
Hey guys, we have a controller that handles two endpoints (`/summary.json` and `/projects/:id/summary.json`). The implementation of both endpoints are very similar, but they return different types. The current version of kommentaar allows to add multiple endpoints to the controller, but doesn't allow multiple response types. Should we break this controller into two controllers or could we change how kommentaar link the endpoints with responses?

```go
// GET /v3/summary ALPHA
// GET /projects/{projectId}/summary ALPHA
// Get the summary dashboard.
//
// Retrieves the summary from the entire installation or for a specific project,
// returning counters about tasks, milestones, columns, events, risks, timers,
// projects healths.
//
// Query: $ref: serializer.SummaryRequestArgsGet
// Response 200 (application/json): $ref: serializer.SummaryDashboardResponseGet
// Response 200 (application/json): $ref: serializer.SummaryProjectDashboardResponseGet
// Response 400 (application/json): $ref: serializer.Error
func (s *Summary) GET(c echo.Context, projectSummary bool) error {
  // ...
```

**Comment by Carpetsmoker** [comment]
The OpenAPI spec supports it, but I'm not sure if it make sense to add support for this. How would I read the documentation? "It can return either this or that"? Sounds confusing to me to be honest.

Comment blocks aren't tied to actual code at all outside of the `$ref` references, so you can just create two comment blocks:

	// GET /v3/summary ALPHA
	// Get the summary dashboard.
	//
	// Query: $ref: serializer.SummaryRequestArgsGet
	// Response 200 (application/json): $ref: serializer.SummaryDashboardResponseGet
	// Response 400 (application/json): $ref: serializer.Error

	// GET /projects/{projectId}/summary ALPHA
	// Get the summary dashboard.
	//
	// Query: $ref: serializer.SummaryRequestArgsGet
	// Response 200 (application/json): $ref: serializer.SummaryProjectDashboardResponseGet
	// Response 400 (application/json): $ref: serializer.Error
	func (s *Summary) GET(c echo.Context, projectSummary bool) error {

**Comment by Carpetsmoker** [comment]
BTW the multiple URL support is mostly intended as a shortcut for cases where two endpoints are exactly the same. I added it while doing some of the Desk v2 API stuff, as many v1 and v2 endpoints were the same.

**Comment by rafaeljusto** [comment]
Thanks for the info @Carpetsmoker , will do the changes here.
