### ISSUE TITLE
How are ye serving the OpenAPI file?

### ISSUE THREAD

**Issue by romanoaugusto88** [Teamwork/kommentaar#28]
Hi lads,

Are ye using an external service to serve the docs or something?
Also, is there already any "good practice" to auto-generate the docs on every commit or something?

Thanks.

**Comment by Carpetsmoker** [comment]
Stoplight.io is the service we're supposed to be using in Teamwork. Holly manages that, and Jordon wrote [a script to upload files to that](https://github.com/Teamwork/strut/tree/master/skel-go/service/bin/stoplight). It's used in CRM.

In Desk we [upload it with the frontend](https://github.com/Teamwork/desk/blob/master/travis/run-operation#L24-L33) (the entire `frontend/public` dir gets uploaded to AWS later), and it available at https://digitalcrew.teamwork.com/desk/public/openapi.yaml

**Comment by romanoaugusto88** [comment]
Thank you :+1:
