### ISSUE TITLE
Support for embedded struct for $ref

### ISSUE THREAD

**Issue by abiosoft** [Teamwork/kommentaar#4]
I'm not sure how complex this would be and I do not think it is important but it would be useful.

Trying to use an `$ref` with a embedded struct panics. 

An example use case is the following.
```
type ticketCreateResponse struct {
    models.TicketAndThreadsJSON
}
```
Note, this may not be needed if #3 is fixed.

**Comment by Carpetsmoker** [comment]
`panics()` are never good, but support for parsing structs is still a bit hacky. Much room for improvement here (current code for that is more prototype, need to rewrite pretty much all of that).
