### ISSUE TITLE
Some docs should be visible for only internal developers

### ISSUE THREAD

**Issue by adam-lynch** [Teamwork/kommentaar#56]
Some things which consume Swagger, etc. have their own add-ons / custom metadata. It would be good to be able to provide these details in the code comment.

Example: 

![screen shot 2018-12-13 at 09 11 22](https://user-images.githubusercontent.com/1427241/49928076-43841500-feb7-11e8-9b5d-c090831f4173.png)

This endpoint would not be "public" in Stoplight.io (it's not visible unless logged in). 

Is there any way we could allow the option for this kind of thing in the code comments?

Alternatively, we could have a convention like `.private.json` and then post-process in another script but that'll be messy if doing it for multiple Stoplight-only properties.

**Comment by Carpetsmoker** [comment]
What does "public" mean, exactly? That it's only available to our devs? Or that it's available to everyone, but they need to log in?

> Is there any way we could allow the option for this kind of thing in the code comments?

Probably; the first idea that I would have is to add a special category for this, e.g. `$private`:

    // POST /activities/{id}.json acivities $private

**Comment by adam-lynch** [comment]
The endpoint doesn't end up in published documentation. It can only be seen by logging into edit ("design") mode. 

Not a bad idea, but I actually need to do some more thinking on what we need/want for sure and I'll come back to you

**Comment by Carpetsmoker** [comment]
Talked to Adam, issue is that some docs should only be visible to our internal Teamwork devs. We could add the `x-stoplight.public: false`, but then it's only visible in the Stoplight editor, which is kinda clumsy for reading API docs. So need to either:

- Upload two files, one with all endpoints which is password-protected, and one with only non-private ones.
- Find another/better way to do this in OpenAPI and/or Stoplight.
