### ISSUE TITLE
RFC: Extend endpoint

### ISSUE THREAD

**Issue by jrdnull** [Teamwork/kommentaar#68]
Proposal for a new directive to allow arbitrary changes to the outputted json/yaml of an endpoint in the spec.

For example:
```go
// POST /path
//
// Request body: reqRef
// Response 200: {empty}
// Extend: extend.yaml
```

Similar to the `schema` param to specify a file, `extend_private.yaml` contains:
```
x-private: true
```

generates from the test:
```
           swagger: "2.0"
            info:
              title: x
              version: x
            consumes:
            - application/json
            produces:
            - application/json
            paths:
              /path:
                post:
                  consumes:
                  - application/json
                  operationId: POST_path
                  parameters:
                  - in: body
                    name: endpoint-extend.reqRef
                    required: true
                    schema:
                      $ref: '#/definitions/endpoint-extend.reqRef'
                  produces:
                  - application/json
                  responses:
                    "200":
                      description: 200 OK (no data)
                  x-private: true
            definitions:
              endpoint-extend.reqRef:
                title: reqRef
                type: object
```

the contents of the file is merged with the endpoint to allow overriding or adding extra data.

---

# Why
This is to allow for cases like https://github.com/Teamwork/kommentaar/issues/56 or any other non standard schema that users want.

# Implementation
I've got a  working implementation locally I'm testing out, it affects the existing output though as due to the way I've implemented it the ordering is lost on the keys in the schema, so I've reordered them alphabetically by the keys to for it to reproduceable output.

# Questions
Does it need to support multiple files? I've currently implemented as just one, but seems like it could be useful if you had multiple files.

---

If everyone is happy with this I'll clean up the implementation and make a PR

**Comment by adam-lynch** [comment]
Sounds good to me. Agree that it doesn't need to handle multiple files yet.

**Comment by romanodesouza** [comment]
Sounds good to me as well, I don't see any blocker for this feature to get implemented.
Regarding the order of the keys, I suppose the parsers out there will not worry about that. Just the reordering could cause some extra noise in diffs but I don't think it's an issue really.

**Comment by ripexz** [comment]
Sounds like a good way to address #56 without committing to vendor-specific params or having separate files 🤔 PR it up I guess 😊

**Comment by jrdnull** [comment]
> Sounds good to me as well, I don't see any blocker for this feature to get implemented.
> Regarding the order of the keys, I suppose the parsers out there will not worry about that. Just the reordering could cause some extra noise in diffs but I don't think it's an issue really.
> 
> I think it should go out with single file support, for now, to address the problem and maybe work more on that if needed.

:+1:, in the end I didn't have to reorder the keys just transform it into a map for merging if its actually got an extend parameter on the endpoint 

its up here https://github.com/Teamwork/kommentaar/pull/70
