### ISSUE TITLE
Unable to parse `ast.InterfaceType`

### ISSUE THREAD

**Issue by ready4god2513** [Teamwork/kommentaar#7]
github.com/teamwork/desk/api/v2/threads/unlike.go: could not parse response 400 params: unknown type: *ast.InterfaceType

See https://github.com/Teamwork/desk/pull/3210

**Comment by Carpetsmoker** [comment]
I'm not even sure if we want to support this to be honest. How should this appear in the resulting OpenAPI docs? I don't even know if they have a syntax for that in the spec?

I think that [this](https://github.com/Teamwork/desk/pull/3210/files#diff-1c7ee07c098f925967d7ea324ddb7e54R13) should just be `[]string` and not `interface{}`?

**Comment by ready4god2513** [comment]
Well, look at the two methods that use it.   The types are completely different.  We *could* have a second type.  I'm not sure what makes sense.

**Comment by abiosoft** [comment]
Can't we do this a lazy way ?
`json.Marshal` the type and then `json.Unmarshal` to generic `map[string]interface{}`. I think it would be easier to traverse `map[string]interface{}`.

**Comment by Carpetsmoker** [comment]
That won't work because the `$object: helper.HTTPErr` is added to the YAML output only *once* (as a "model"), and endpoints refer to it.

See the example here: https://app.swaggerhub.com/apis/Teamwork/teamwork-desk/2.0#/customers/POST_desk_v1_customers_json

**Comment by Carpetsmoker** [comment]
I've added a clearer message which says that we don't support `interface{}`. I don't think we're going to need this any time soon and supporting it will require a lot of work.

We can always revisit this if we *really* need it.
