### ISSUE TITLE
Project still maintained ?

### ISSUE THREAD

**Issue by adrianlungu** [Teamwork/kommentaar#87]
Is this project still being used or maintained ?

I like that it has more up-to-date implementations vs. go-swagger and is also somewhat more flexible in parsing code to OpenAPI spec, but I'm not sure if there are any plans on keeping it maintained or updated and I see there's little discussion as of late here ?

**Comment by rafaeljusto** [comment]
Hi Adrian, we still use this tool frequently in our internal projects, so if you find any issues with it please let us know.

**Comment by adrianlungu** [comment]
Hello Rafael, thanks for getting back to me. 

I'm still exploring some of the internals of the project. 

There are a couple of things I'm looking at either adding or maybe you guys also need them and then maybe they'll be added to the roadmap, i.e.:

- Support for retrieving `enum` from the code by identifying consts for a specific type part of a struct
- Support for OpenAPI v3 mainly because v2 does not have support for HTTP cookie security definition
- Support for optionality via pointers, in some cases, an endpoint may return a pointer to a struct, which, if nil, would return nil
- Support for roles via documentation

These are some of the things I'm looking into right now, any feedback on them is greatly appreciated. 

I already have a fork with some updates in it where I modified the `regex` to allow also setting a `custom description` for a response, as in some cases, additional information may be needed outside of the HTTP code.

**Comment by adrianlungu** [comment]
> What we usually do is manually set the enum, like:

I wonder if this can't be automated using go ast 🤔 

> I would expect that when you don't have the returned entity, you would return 404 or some other HTTP status. 🤔

That's a very good point!

> Yeah, this also not in our roadmap. We are currently only maintaining the project without adding new features. But we do accept contributions 🙂 .

Do you have a preferred contributions flow ? 

Should we create `Issues` in the repo for any features we'd like to have ? 

Is there a form of voting for any specific features that would make it in the repo vs features that would not be added ?

Thanks!

**Comment by rafaeljusto** [comment]
> I wonder if this can't be automated using go ast 🤔

We would need to look for all variable declarations of the specific type in the same file. And it's not guaranteed that the type alias is an actual enum, so it could be tricky to implement.

> Do you have a preferred contributions flow ?

We don't have an official contributor's guidelines (but we should 😄 ). But that's a good suggestion, raising an issue describing the issue before creating a PR helps to generate discussion that could actually save time before coding the solution.

> Is there a form of voting for any specific features that would make it in the repo vs features that would not be added ?

Nop. I guess creating issues with feature requests and letting the community react with emojis to the issue would be the way Github give us to identify what people are looking for 🤔

**Comment by adrianlungu** [comment]
Awesome, thanks for the feedback @rafaeljusto 

I'll close this issue and open a few others with the various suggestions made.
